services:
  mongo:
    image: mongo:7
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

  backend:
    build: ./backend
    environment:
      MONGO_URL: mongodb://mongo:27017/hotelDB
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data: