apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: hotel-app
spec:
  clusterIP: None
  selector:
    app: mongo
  ports:
    - port: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: hotel-app
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      securityContext:
        runAsUser: 0
      initContainers:
        - name: copy-keyfile
          image: mongo:7
          command:
            - sh
            - -c
            - "cp /secret-source/key.file /keydir/key.file && chmod 400 /keydir/key.file && chown 999:999 /keydir/key.file"
          volumeMounts:
            - name: mongo-keyfile-secret
              mountPath: /secret-source
            - name: mongo-keyfile-ready
              mountPath: /keydir
      containers:
        - name: mongo
          image: mongo:7
          args: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile/key.file"]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-keyfile-ready
              mountPath: /etc/mongo-keyfile
      volumes:
        - name: mongo-keyfile-secret
          secret:
            secretName: mongo-keyfile
        - name: mongo-keyfile-ready
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi