apiVersion: v1
kind: Pod
metadata:
  name: mongo-debug
  namespace: hotel-app
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: mongo
      image: mongo:7
      command: ["sleep", "3600"]
      volumeMounts:
        - name: mongo-keyfile
          mountPath: /etc/mongo-keyfile/key.file
          subPath: key.file
          readOnly: true
  volumes:
    - name: mongo-keyfile
      secret:
        secretName: mongo-keyfile
        defaultMode: 0400